# Load data

In [76]:
import pandas as pd

In [77]:
df=pd.read_csv("../data/kpop.csv")
df.head()

,stage_name,full_name,korean_name,korean_stage_name,birth_date,group,country,height,weight,birth_place,gender,instagram_username
0,Taeyeon,Kim Taeyeon,김태연,태연,3/9/1989,SNSD,South Korea,160,44,Jeonju,F,taeyeon_ss
1,Sunny,Lee Sunkyu,이순규,써니,5/15/1989,SNSD,South Korea,158,43,California,F,svnnynight
2,Tiffany,Hwang Miyoung,황미영,티파니,8/1/1989,SNSD,South Korea,163,50,San Francisco,F,xolovestephi
3,Hyoyeon,Kim Hyoyeon,김효연,효연,9/22/1989,SNSD,South Korea,158,48,Incheon,F,watasiwahyo
4,Yuri,Kwon Yuri,권유리,유리,12/5/1989,SNSD,South Korea,167,45,Goyang,F,yulyulk

In [78]:
df.nunique()

stage_name            1398
full_name             1574
korean_name           1557
korean_stage_name     1303
birth_date            1467
group                  268
country                 16
height                  39
weight                  47
birth_place            155
gender                   2
instagram_username     150
dtype: int64

In [79]:
group=df['group']
group.describe()

count     1528
unique     268
top        NCT
freq        20
Name: group, dtype: object

In [80]:
group.str.upper()

0           SNSD
1           SNSD
2           SNSD
3           SNSD
4           SNSD
          ...
1661    NEWJEANS
1662    NEWJEANS
1663    NEWJEANS
1664    NEWJEANS
1665    NEWJEANS
Name: group, Length: 1666, dtype: str

In [81]:
group.str.upper().nunique()

267

In [82]:
# Show values that appear more than once
counts = df['group'].value_counts()
counts[counts > 1]

group
NCT             20
14U             14
Cosmic Girls    13
Seventeen       13
LOONA           12
                ..
Bolbbalgan4      2
Busters          2
TVXQ             2
B.O.Y            2
Rockit Girl      2
Name: count, Length: 265, dtype: int64

In [83]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [stage_name, full_name, korean_name, korean_stage_name, birth_date, group, country, height, weight, birth_place, gender, instagram_username]
Index: []

In [84]:
repeat=group.nunique()-group.str.upper().nunique()

In [85]:
repeat

1

In [86]:
groups = df["group"].dropna()
groups.nunique()

268

In [87]:
collisions=groups.groupby(groups.str.upper()).unique()
collisions[collisions.apply(len)>1]

group
NATURE    [Nature, NATURE]
Name: group, dtype: object

In [88]:
df['group']=df['group'].str.strip().str.upper()

In [89]:
df['group'].nunique()

267

In [90]:
df["country"].nunique()-df['country'].str.upper().nunique()

0

No issues with country

In [91]:
df.head()

,stage_name,full_name,korean_name,korean_stage_name,birth_date,group,country,height,weight,birth_place,gender,instagram_username
0,Taeyeon,Kim Taeyeon,김태연,태연,3/9/1989,SNSD,South Korea,160,44,Jeonju,F,taeyeon_ss
1,Sunny,Lee Sunkyu,이순규,써니,5/15/1989,SNSD,South Korea,158,43,California,F,svnnynight
2,Tiffany,Hwang Miyoung,황미영,티파니,8/1/1989,SNSD,South Korea,163,50,San Francisco,F,xolovestephi
3,Hyoyeon,Kim Hyoyeon,김효연,효연,9/22/1989,SNSD,South Korea,158,48,Incheon,F,watasiwahyo
4,Yuri,Kwon Yuri,권유리,유리,12/5/1989,SNSD,South Korea,167,45,Goyang,F,yulyulk

In [93]:
df.drop(columns=['height', 'weight'])

,stage_name,full_name,korean_name,korean_stage_name,birth_date,group,country,birth_place,gender,instagram_username
0,Taeyeon,Kim Taeyeon,김태연,태연,3/9/1989,SNSD,South Korea,Jeonju,F,taeyeon_ss
1,Sunny,Lee Sunkyu,이순규,써니,5/15/1989,SNSD,South Korea,California,F,svnnynight
2,Tiffany,Hwang Miyoung,황미영,티파니,8/1/1989,SNSD,South Korea,San Francisco,F,xolovestephi
3,Hyoyeon,Kim Hyoyeon,김효연,효연,9/22/1989,SNSD,South Korea,Incheon,F,watasiwahyo
4,Yuri,Kwon Yuri,권유리,유리,12/5/1989,SNSD,South Korea,Goyang,F,yulyulk
...,...,...,...,...,...,...,...,...,...,...
1661,Minji,Kim Minji,김민지,민지,5/7/2004,NEWJEANS,South Korea,Yeongwol,F,NaN
1662,Hanni,Pham Ngoc Han,팜응옥헌,하니,10/6/2004,NEWJEANS,Vietnam,Melbourne,F,NaN
1663,Danielle,Mo Jihye,모지혜,다니엘,4/11/2005,NEWJEANS,South Korea,Munsan,F,NaN
1664,Haerin,Kang Haerin,강해린,해린,5/15/2006,NEWJEANS,South Korea,Gimcheon,F,NaN
1665,Hyein,Lee Hyein,이혜인,혜인,4/21/2008,NEWJEANS,South Korea,Incheon,F,NaN

In [94]:
df.to_csv("../data/processed/kpop.csv", index=False)

In [95]:
df2=pd.read_csv("../data/processed/kpop.csv")
print(df2.head())

  stage_name      full_name korean_name korean_stage_name birth_date group  \
0    Taeyeon    Kim Taeyeon         김태연                태연   3/9/1989  SNSD
1      Sunny     Lee Sunkyu         이순규                써니  5/15/1989  SNSD
2    Tiffany  Hwang Miyoung         황미영               티파니   8/1/1989  SNSD
3    Hyoyeon    Kim Hyoyeon         김효연                효연  9/22/1989  SNSD
4       Yuri      Kwon Yuri         권유리                유리  12/5/1989  SNSD

       country  height  weight    birth_place gender instagram_username
0  South Korea     160      44         Jeonju      F         taeyeon_ss
1  South Korea     158      43     California      F         svnnynight
2  South Korea     163      50  San Francisco      F       xolovestephi
3  South Korea     158      48        Incheon      F        watasiwahyo
4  South Korea     167      45         Goyang      F            yulyulk